### ISSUE TITLE
-fsanitize=undefined unsupported by clang on OS X

### ISSUE THREAD

**Issue by veorq** [P-H-C/phc-winner-argon2#103]
Noticed this while doing quick tests of test functions, haven't investigated the best solution:

```
✗ make testci
cc -std=c89 -pthread -O3 -Wall -g -Iinclude -Isrc  -Werror=declaration-after-statement -D_FORTIFY_SOURCE=2 -Wextra -Wno-type-limits -Werror -fsanitize=address -fsanitize=undefined src/argon2.c src/core.c src/blake2/blake2b.c src/thread.c src/encoding.c src/ref.c src/test.c -o testcase
clang: error: unsupported argument 'undefined' to option 'fsanitize='
make: *** [testci] Error 1
✗ clang -v
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin15.3.0
Thread model: posix
```

**Comment by technion** [comment]
This is pretty much the reason for a024628f, and was discussed in the PR for #102.

tests in general can be run as per the README:

    make test

The CI environment, which provides for stronger checks, was given a dedicated make target so that these flags don't interfere with portability to systems such as OSX.

**Comment by veorq** [comment]
thanks, I missed this :)
