### ISSUE TITLE
Document the intended use of associated data in contrast to the salt/nonce

### ISSUE THREAD

**Issue by vks** [P-H-C/phc-winner-argon2#151]
Looking at the spec, the associated data seems to enter the algorithm differently than the nonce/salt. However, it is not clear to me what their conceptual difference is: Couldn't I just append the associated data to the salt? Why does Argon2 have an additional parameter for the associated data?

**Comment by SparkDustJoe** [comment]
["not an official developer on this project" disclaimer]
In the case of Skein and a number of other algorithms, it could be envisioned as a way to "tag" a group of hashes to a particular system or process.  In this way, the 1000's of password hashes will all be different with different salts, but "LOGIN FOR PRODUCTION" and some other very specific system information could be used to differentiate the results from other processes within the organization.  This prevents altering the salt in any way, but also doesn't provide a "shortcut" path for precomputing or rainbow tables, and allows a site owner to make their hashes different from everyone else's while still following a standardized procedure.  In Skein that "block" was called "Personalization"

Another use would be to tie a hash to a given Public Key, or another hash used as a signature or MAC, something not necessarily private.

There is in the spec a separate slot for Secret which would be the equivalent of using this as a password derivation function from a master password, or tying the hash to a given Private Key.

**Comment by vks** [comment]
I still don't get why you wouldn't just append everything to the (random) salt. Why is it desirable to not alter the salt?

**Comment by sneves** [comment]
You can certainly cram all of the information you want into the salt, but it's often better to use different fields for different purposes, to avoid confusion.

The purpose of the salt is to randomize the password hash. Therefore, it must always be unique for each password.

The associated data, on the other hand, does not need to be unique, or even exist for that matter. As @SparkDustJoe said, it might be useful to separate between different hashes for different websites / privileges / whatever.

**Comment by SparkDustJoe** [comment]
I'll add this after reading about two SQL injection attack examples in the last 5 years.  In a user database you typically store the encrypted (still a bad idea) or hashed and salted password for each user, we all know that.  The salt is unique to each user and completely random, but because it's random is has to be persisted for later attempts.  If the hashing algorithm is known and an attacker can inject himself as an admin, or reset the admin account to give himself access, then the system starts to fall apart real quick, as now an attacker can attempt to reverse each password through dictionaries or brute hashCat force (40 BILLION MD5 hashes/sec on $6000 hardware), or simply reset choice passwords to one of the attackers choosing (maybe for a user who was previously disabled or hasn't logged in in a while).  Being able to see the user table is bad enough, and reported in the news all the time (LinkedIn, Yahoo, Adobe, Ashley Madison, the list goes on).  But you have to know the result of the hash AND the salt in order to check a "legitimate" user's login attempt, so there's no way to get around storing them SOMEWHERE, it's unavoidable.

Using the Associated Data or Secret fields, however, allows you to inject an additional parameter not known to the attacker, and without which no attempt will succeed without raising alarms or locking accounts.  It can be a constant for a given purpose, but doesn't have to be stored with the user, and each user still has their unique salt.  The best of both keeping information away from an attacker, and having randomization for each user.

Yes, you could just put that constant into the Salt, but that requires additional processing and buffer manipulation for EVERY login, needlessly.  If the password function already has parameter inputs, then why not let the library do that work for you. What I have read about and seen in the news time and time again is developers trying to "get creative" with a given algorithm to attempt to increase security, only to botch the implementation and hand the keys to the attacker in the end.  If this additional injection of data can be done at the library level, this removes any need for the implementer to "get creative" with how to incorporate it into the login logic.  If that additional data is guaranteed to provide additional entropy and can be kept away from prying eyes snooping around with scripts or leaked database tables, all the better.  In fact I would argue that Additional Data renders any leaked user tables completely useless without the accompanying code-base and/or documentation for the targeted system.  

@khovratovich @veorq Would you guys agree with that assessment?

Just my $0.02 USD....

**Comment by Leont** [comment]
> Using the Associated Data or Secret fields, however, allows you to inject an additional parameter not known to the attacker

I don't think the Associated Data field does this. The hash encoded output will contain a "data=" field with the associated data (though `argon2_encodedlen` doesn't seem to take this into account)

**Comment by sneves** [comment]
`argon2_encodedlen` is meant to be used with `argon2_hash`, which does not include rarely used fields such as `ad` or `secret`. Those need `argon2_ctx`.

**Comment by SparkDustJoe** [comment]
You also don't have to store the fully encoded output if the parameters don't change within a system (parallelism/threads, iterations/timecost, memory, ad, etc.).  If everything else stays the same, you only need the attempted password and the salt as variable inputs from the "user", and the resulting hash and salt as the storage field values.

**Comment by SparkDustJoe** [comment]
@Leont A system should never just spit that result out in the raw to an attacker (although if you store it raw, he, admittedly, may get it from a SQL dump, hence my comment that if those time/memory/parallelism values don't change, then don't store them unless you have to, or put them in a different "parameter type" table with "1" being 65536, 16, 4 and "2" being 8192,  64, 4, etc. as an example).

**Comment by aberaud** [comment]
To be clear, is this field just a semantic thing or does it have any actual cryptographic implications that would make it different from appending to the salt ?

**Comment by SparkDustJoe** [comment]
You will get drastically different results (due to processing order and input lengths being folded into the input stream) if you append the data to the Salt vs. the Associated Data input.

**Comment by josephlr** [comment]
@aberaud @SparkDustJoe Using the Associated Data will give you a different value than just appending the Associated Data to the salt, but as far as I can tell the cryptographic properties are exactly the same. It's just an issue of the folding order as @SparkDustJoe said.

One thing about not using the Associated Data and Secret fields, is that you can then use the `argon2_verify` and `argon2_hash` classes of functions. You can also get nice encoded strings, which you don't get if you use the raw calls to the `argon2_ctx` functions.

As for closing this issue, it would seem that all is needed is an explanation in the README as to the intended use of Associated Data. It doesn't seem like any code itself is buggy. Would you all agree?

**Comment by vks** [comment]
Yes, from the code it is clear that it is different from appending to the
salt. The intended use and cryptographic properties compared to the salt
are not very clear. This is mostly a documentation issue

**Comment by SparkDustJoe** [comment]
@josephlr Yes, the issue is about documentation.  Analysis regarding the benefits of the AD or Secret is a different ball of wax.

**Comment by 40417711** [comment]
Can AssociatedData be used as a Pepper based of this then?
