### ISSUE TITLE
version parameter

### ISSUE THREAD

**Issue by philtay** [P-H-C/phc-winner-argon2#157]
I'm not sure if the https://github.com/P-H-C/phc-string-format repo is still maintained, thus I'm opening [the same issue](https://github.com/P-H-C/phc-string-format/issues/1) here. The problem is that the recently introduced v=19 parameter doesn't adhere to the official string format and is not documented. This, in turn, makes difficult things like writing a reliable regex to validate an argon2 hash in modular crypt format.

**Comment by ranisalt** [comment]
I currently use [this regex](https://github.com/ranisalt/node-argon2/blob/master/index.js#L57) to check for a hash in the format, but it's not the most precise thing in the world.

**Comment by philtay** [comment]
Thanks for your reply and I concur with you: it's not the most precise thing in the world! ;)
At least you should use `[a-zA-Z0-9/+]` instead of `[\w/+]`. `\w` matches the underscore character too.
IMO the official string format spec should provide a standard regex too. Problem is... we don't even have a complete standard as of today.

**Comment by sneves** [comment]
The other repo is definitely outdated; the most up to date specification is (sigh...) in the [source code](https://github.com/P-H-C/phc-winner-argon2/blob/master/src/encoding.c#L226-L245).

**Comment by YetAnotherMinion** [comment]
It is pretty annoying that this org comes up with a good format for hash fingerprints that is broadly compatible with other hash libraries -- with, I might add a well defined format for specifying arbitrary and additional key-value data -- and then dumps that format on the side of the road and drives off into the night with its new key value pair stuffed arbitarily into its own section.

Now my parser has its first special case for your hash function format because you could not play ball and remember that key value pairs go in their own dedicated section. What is so special about your logic that you cannot defer processing the version number by 10-20 steps of the parsing automata?

**Comment by ranisalt** [comment]
I don't know why the version isn't just a parameter, before time/memory/lane cost instead of in another section of the hash.

**Comment by YetAnotherMinion** [comment]
It is not before the time/memory/lane section because they have a linear parser where they advance the char* by a fixed offset, check if the parameter is at exactly that offset, otherwise fail. Its really quick hack to write, but in this case there is no business reason to not just make N passes over the key value section looking for a specific key where N is the number of keys you expect.

**Comment by tniswong** [comment]
For anyone interested, Here's a pretty good regex:

`^(?:\$([a-z0-9-]+)){1}(?:\$v=([a-z0-9]+))?(?:\$([a-zA-Z0-9/+.-=,]*[^,]))?(?:\$([a-zA-Z0-9/+.-]+)){1}(?:\$([a-zA-Z0-9/+.-]+)){1}$`

Match Indexes:

1. The id of the hashing algorithm
1. The (optional) version of the hashing algorithm (does not include the `v=`). This assumes alphanumerics, because the spec isn't clear about this part of the format.
1. The (optional) parameters (comma separated list of `key=value` pairs)
1. The salt
1. The hash

**Comment by ranisalt** [comment]
@simonepri whoa, thanks mate, that will be definitely useful.

**Comment by simonepri** [comment]
@rainsalt Do you believe that the usage of the raw option is a good workaround? Have you some ideas on how to achieve this in other ways?

I'm looking for some feedbacks about the API.

**Comment by simonepri** [comment]
@ranisalt Do you believe that the usage of the raw option is a good workaround? Have you some ideas on how to support out of specs fields in other ways?

I'm looking for some feedback about the API.

**Comment by simonepri** [comment]
@ranisalt I've improved it and I've added the 'strict' parameter in the deserializer.

Now you can use it also to parse MCF formatted string
For example:
`$pbkdf2-sha256$6400$0ZrzXitFSGltTQnBWOsdAw$Y11AchqV4b0sUisdZd0Xr97KWoymNE0LNNrnEgY4H9M`
will generate
```
{
  id: 'pbkdf2-sha256',
  raw: '6400',
  salt: Buffer.from('0ZrzXitFSGltTQnBWOsdAw', 'base64'),
  hash: Buffer.from('Y11AchqV4b0sUisdZd0Xr97KWoymNE0LNNrnEgY4H9M', 'base64'),
}
```

If the strict mode is on, you can only parse strings that perfectly adhere to the 'standard'.

**Comment by ranisalt** [comment]
Please let's move this discussion to your repo.
