### ISSUE TITLE
autotools build framework

### ISSUE THREAD

**Issue by 0-wiz-0** [P-H-C/phc-winner-argon2#22]
Please take a look at my fork, which contains a basic autotools framework for argon2.
kats/test.sh needs to be converted to work with this.
And it's currently a configure flag (--enable-optimization) to decide if opt.c or ref.c is used.

**Comment by veorq** [comment]
Thanks, checking this out

**Comment by veorq** [comment]
autoconf fails here (OSX, clang):
```
$ autoconf
configure.ac:13: error: possibly undefined macro: AM_CONDITIONAL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:15: error: possibly undefined macro: AM_CFLAGS
configure.ac:17: error: possibly undefined macro: AM_INIT_AUTOMAKE
configure.ac:19: error: possibly undefined macro: AC_PROG_LIBTOOL
```

Given the relative simplicity of the project, I'm not sure that the benefit of an autotools build is worth the extra hassle (and incompatibility with autotoolsless systems). Not an expert in build frameworks though.

**Comment by sneves** [comment]
Use `autoreconf -fvi`; that works here.

**Comment by 0-wiz-0** [comment]
Sorry, I should have been more explicit how to use this.
You need to have autoconf, automake, and libtool installed.
``autoreconf -fiv`` is indeed the easiest way to call the tools in the right order.
Then you do
````
./configure
make
make check
make install
````
If you want the optimized version, run configure with the ``--enable-optimization`` flag.

``make check`` will currently fail because the test script wants to build genkat (in two ways) and assumes being called with a different path. This needs to be adapted in some way, but I've left this alone for now. Help here would be appreciated.

**Comment by technion** [comment]
Can I please make a feature request that you pre-build and check in the ./configure script?

I appreciate it was the original GNU intent that developers build this themselves and it just gets bundled with releases, but I raise several issues with that:

* Autoconf scripts nearly always end up tied to specific or at least minimal versions of autoconf. It's shocking how much software I am unable to build even on RedHat 6 due to the LTS versions they deploy. This codebase was specified with C89 presumably for maximum compatibility, it's contradictory to that to wait for a release before testing on anything but a modern system
* Building a release that contains files not present in git is contradictory to modern workflows

**Comment by technion** [comment]
To add to my "autoconf version" point, please see this issue in testing your branch:

    $ autoreconf -V
    autoreconf (GNU Autoconf) 2.69
    $ autoreconf -fvi
    libtoolize: Consider adding '-I m4' to ACLOCAL_AMFLAGS in Makefile.am.
    Unescaped left brace in regex is deprecated, passed through in regex; marked by <-- HERE in m/\${ <-- HERE ([^ \t=:+{}]+)}/ at /usr/bin/automake line 3936.

Note also your edition pulls -std=C89 out of the build flags, which may have unintended consequences around reducing out of the box portability.

**Comment by 0-wiz-0** [comment]
I'd really rather not.
'configure' is not the only file that would have to be added, there are quite a number of other files (Makefile.in, some m4 files, libtool support files) that would need to be added.
The variables used so far should be quite portable to old autotool versions.

I don't support your statement about 'modern workflows' at all.

About your 'Unescaped left brace' warning, that is not fixed in the latest release, we'll have to wait for a newer one. The libtoolize warning is harmless, you can ignore it.

About c89 -- I got a comment that the flag as used is not portable, and since I would assume that every compiler in use today supports at least C 89, I don't find it useful, which is why I removed it.

**Comment by sneves** [comment]
Regarding `-std=c89`, that was intended to ensure that the whole codebase was as lowest-common-denominator as possible. Whatever compilers default to should be OK here (and if we were going to be absolutely strict about C89, `stdint.h` and `long long` could not be used, for instance).

**Comment by technion** [comment]
@sneves : Yes, that's my point. C99 features could easily (arguably, likely) slip in if autoconf decides it's not a required flag on developer's machines and removes it from the build going forward.

In line with the "lowest common denominator" comment, lets say I want to test on an old, uncommon, or otherwise autoconf-less platform - is the expectation that I would wait for someone to tag 1.0 release before identifying it as incompatible?

**Comment by veorq** [comment]
No intent to use autotools for the moment.

**Comment by 0-wiz-0** [comment]
That's a pity. Good luck with the cross-platform library building without using libtool.

**Comment by veorq** [comment]
We'll investigate different options, including autotools and cmake. Just closing the respective issues as the discussions stalled.
