### ISSUE TITLE
Decrypting argon2?

### ISSUE THREAD

**Issue by zachariapopcorn** [P-H-C/phc-winner-argon2#311]
How do you decrypt a string that's encrypted with argon 2, or is it not possible?

**Comment by SparkDustJoe** [comment]
I think you mean encoded, because Argon2 is a hash function. It is
non-reversable by design. It's meant to hash a password into an encoded
string that can only be compared to another encoded string. If they match,
the inputs to Argon2 we're the same, but you don't ever know what those
inputs were. This is standard hashed password storage practice.

**Comment by D-Nice** [comment]
From a pure technical perspective, and playing somewhat devil's advocate, it could be utilized in a Feistel Network for encryption scheme purposes, however, I have a feeling this isn't what you were talking about and on its own, it's *just* a memory hard key derivation function.

Or quite simply, a one-way function.
