### ISSUE TITLE
Use CMake

### ISSUE THREAD

**Issue by SamuelMarks** [P-H-C/phc-winner-argon2#38]
In reference to #22, and other questions requesting support for one IDE or the other, why don't we just use CMake?

Started converting your Makefile line-by-line [pretty much] to a CMakeLists.txt. Here's the [gist of it](https://gist.github.com/SamuelMarks/9c3011a9fe9a5ac80d17).

It's not fully functional yet, which explains the lack of PR. Creating an issue to start the discussion.

**Comment by jedisct1** [comment]
Why not Gyp? Why not Scons?

The problem with CMake, Gyp, Scons and other alternatives is that they are awesome if you are familiar with them. 

But most people aren't. They will struggle to understand how to compile the project, change the compile flags, build a distribution, run the tests, change the install location, cross-compile, integrate that with their CI system, build packages for their favorite OS/distro.

Autotools are ugly, and other tools can achieve the same result (plus: spit out Xcode and MSVC solutions) with less lines of code and better readability.

However, for compiling C/C++ code, most people expect a standard `./configure` script.

So, unless Gyp/Scons/CMake solve an actual problem that autotools don't, I would still recommend sticking with autotools, and offering tarballs of releases for download. This project is simple enough that the build system doesn't really matter; even the autoconf script is super simple and won't require much tweaks in the future.

**Comment by SamuelMarks** [comment]
Good thing I asked before spending time on getting it ready for an actual PR.

**Comment by jedisct1** [comment]
Don't close this ticket!

That was just my input based on my experience.

Other people may have a very different opinion.

**Comment by SamuelMarks** [comment]
IMHO proper cross-platform build systems make it easier to integrate with IDEs, different OSs, and other projects.

I am using both gyp and CMake for an argon2 wrapper at the moment, generally you choose the build-system of the parent project [you are integrating it with].

**Comment by technion** [comment]
In the interest of discussion, I like to start with - what system does this library not build on now? The only such issue I am aware of is #37. Does this CMake harness solve that?

**Comment by veorq** [comment]
Thanks @SamuelMarks for offering this! Ideally we should have a proper build system rather than a boring static makefile. I'm wondering, however, about the cost-benefit ratio: should we force users to have cmake installed, or to use python (for scons), or to have to deal with autotools, just to have a more portable project? In the current state we're supporting a large part of "common" systems with our simplistic makefile. What kind of configurations not covered today would be covered thanks to a more complex build system? (Sorry if that sounds like a silly question, I'm really not much familiar with build scripts.)

**Comment by SamuelMarks** [comment]
Just to throw a spanner in the works, you can ship e.g.: `CMakeLists.txt` AND the Makefile it generates.

That way you won't inconvenience existing users with system dependencies and everyone else benefits with advantages aforementioned ;)

**Comment by jedisct1** [comment]
Beyond not being portable across make implementations, I'm not sure that this will let you change the compiler, compilation flags, and paths.

**Comment by SamuelMarks** [comment]
I'm not a CMake expert, but AFAIK you can do all those same configurations. See the gist I posted initially, it sets the flags correctly, in much the same way as your Makefile.

**Comment by technion** [comment]
@veorq  As someone writing Ruby bindings, scons in particular would be frustrating - a Gem won't gain much traction if it's dependant on Python.

**Comment by sneves** [comment]
This issue is independent of #37. The Microsoft compiler simply warns about different things than GCC and Clang.

As I see it, the main utility of a build system here is to not have to know what the correct command line sequence for (dynamic) linking is. There are no major configuration options to find out about the environment (perhaps except `ref` vs `opt`), and things are mostly portable. I prefer CMake, for what it's worth, but in general it's difficult to see the point of including any such thing. I would probably not reject a properly functioning one, though, if it's not a pain to maintain.

**Comment by technion** [comment]
>perhaps except  ref  vs  opt  

Perhaps that's worth investigating further. A build environment that compiled with OPT, if and only if the hardware fully supported it, has a lot to gain.

Although neither the CMake or autoconf solutions proposed currently address that, I'm guessing the potential is there.

**Comment by veorq** [comment]
No intent to use cmake for the moment.
